### ISSUE TITLE
お願い

### ISSUE THREAD

**Issue by gmpt6524** [P-nutsK/Scratch-Last-login#9]
お願いがあります。
ウェブストアで公開してほしいです。
そうでないと、追加できません。
デベロッパーモードをブロックされています

**Comment by P-nutsK** [comment]
アカウントはあるので多分できる
多分忘れるから明日も連絡して

**Comment by gmpt6524** [comment]
> アカウントはあるので多分できる 多分忘れるから明日も連絡して

(._.)

**Comment by P-nutsK** [comment]
ok作業するべ

**Comment by P-nutsK** [comment]
審査に出しました。
1日以内に公開できる予定です。

**Comment by gmpt6524** [comment]
ありがとうございます。
できたらリンクほしいです

**Comment by P-nutsK** [comment]
審査に通り次第掲載する予定です
もうしばらくお待ちしてください

**Comment by P-nutsK** [comment]
[scratch 生存確認
](https://chrome.google.com/webstore/detail/scratch-%E7%94%9F%E5%AD%98%E7%A2%BA%E8%AA%8D/bckmjnfapmpnkjlhghbdbdemkjmkmdal/)を公開しました。
これで大丈夫ですか？

**Comment by arch-herobrine** [comment]
アプデしろメッセージ表示するやつChrome webstoreにあるやつなら自動でアプデはいるから必要ない説()

**Comment by P-nutsK** [comment]
だからウェブストア版はそれオミットしてる
https://github.com/P-nutsK/Scratch-Last-login/tree/chrome-website-publish-ver
